"""add long term memory facts

Revision ID: 15163e694982
Revises: add31bc25926
Create Date: 2026-07-27 23:35:33.844193
"""
from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

revision: str = '15163e694982'
down_revision: Union[str, Sequence[str], None] = 'add31bc25926'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('memory_facts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('conversation_id', sa.String(length=36), nullable=True),
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('value', sa.String(length=500), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], ),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', 'key')
    )
    op.create_index(op.f('ix_memory_facts_conversation_id'), 'memory_facts', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_memory_facts_tenant_id'), 'memory_facts', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_memory_facts_user_id'), 'memory_facts', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_memory_facts_user_id'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_tenant_id'), table_name='memory_facts')
    op.drop_index(op.f('ix_memory_facts_conversation_id'), table_name='memory_facts')
    op.drop_table('memory_facts')
    # ### end Alembic commands ###
